export type NutritionTopic =
  | 'intro'
  | 'factors'
  | 'lifecycle'
  | 'malnutrition'
  | 'undernutrition'
  | 'sam'
  | 'ncd'
  | 'ghana';

export const TOPIC_LABELS: Record<NutritionTopic, string> = {
  intro: 'Introduction to Nutrition & Health',
  factors: 'Factors Influencing Food Consumption',
  lifecycle: 'Nutrition Throughout the Lifecycle',
  malnutrition: 'Malnutrition: Types, Causes, Consequences',
  undernutrition: 'Undernutrition & Micronutrient Deficiencies',
  sam: 'Management of Severe Acute Malnutrition',
  ncd: 'Overnutrition & Diet-Related NCDs',
  ghana: 'Nutrition Interventions in Ghana',
};

export interface MCQuestion {
  id: string;
  topic: NutritionTopic;
  type: 'mcq';
  prompt: string;
  choices: string[];
  correctIndex: number;
  rationale: string;
}

export interface TFQuestion {
  id: string;
  topic: NutritionTopic;
  type: 'tf';
  prompt: string;
  correctAnswer: boolean;
  rationale: string;
}

export type NutritionQuestion = MCQuestion | TFQuestion;

export const nutritionQuestions: NutritionQuestion[] = [
  // ============================================================
  // INTRO TO NUTRITION & HEALTH (25)
  // ============================================================
  {
    id: 'intro-001',
    topic: 'intro',
    type: 'mcq',
    prompt: 'How many kilocalories does 1 gram of carbohydrate provide?',
    choices: ['4 kcal', '7 kcal', '9 kcal', '2 kcal'],
    correctIndex: 0,
    rationale: 'Carbohydrate and protein each yield approximately 4 kcal/g; fat 9 kcal/g; alcohol 7 kcal/g.',
  },
  {
    id: 'intro-002',
    topic: 'intro',
    type: 'mcq',
    prompt: 'How many kilocalories does 1 gram of fat provide?',
    choices: ['4 kcal', '7 kcal', '9 kcal', '5 kcal'],
    correctIndex: 2,
    rationale: 'Fat is the most energy-dense macronutrient at 9 kcal/g.',
  },
  {
    id: 'intro-003',
    topic: 'intro',
    type: 'mcq',
    prompt: 'How many kilocalories does 1 gram of alcohol contribute?',
    choices: ['4 kcal', '7 kcal', '9 kcal', '0 kcal'],
    correctIndex: 1,
    rationale: 'Alcohol provides 7 kcal/g — closer to fat than carbohydrate.',
  },
  {
    id: 'intro-004',
    topic: 'intro',
    type: 'mcq',
    prompt: 'A patient consumes 25 g protein, 60 g carbohydrate, and 40 g fat in one meal. What is the total energy content?',
    choices: ['460 kcal', '700 kcal', '500 kcal', '620 kcal'],
    correctIndex: 1,
    rationale: '(25 × 4) + (60 × 4) + (40 × 9) = 100 + 240 + 360 = 700 kcal.',
  },
  {
    id: 'intro-005',
    topic: 'intro',
    type: 'mcq',
    prompt: 'Which statement best defines "nutrition"?',
    choices: [
      'The science of food and its relationship to health',
      'The application of dietary therapy in disease',
      'The biochemical study of metabolism only',
      'The cultural significance of food',
    ],
    correctIndex: 0,
    rationale: 'Nutrition is the scientific discipline concerned with food, nutrients, and their relationship to health, growth, and development.',
  },
  {
    id: 'intro-006',
    topic: 'intro',
    type: 'mcq',
    prompt: 'Which term refers to the application of the science of nutrition to humans in health and disease?',
    choices: ['Nutrition', 'Dietetics', 'Metabolism', 'Anthropometry'],
    correctIndex: 1,
    rationale: 'Dietetics applies nutrition science to humans in both health and disease states.',
  },
  {
    id: 'intro-007',
    topic: 'intro',
    type: 'mcq',
    prompt: 'Which of the following is a non-energy yielding nutrient?',
    choices: ['Carbohydrate', 'Protein', 'Fat', 'Vitamins'],
    correctIndex: 3,
    rationale: 'Vitamins and minerals do not provide energy; they are non-energy yielding nutrients essential for biochemical processes.',
  },
  {
    id: 'intro-008',
    topic: 'intro',
    type: 'mcq',
    prompt: 'Which of the following is classified as a macronutrient?',
    choices: ['Vitamin A', 'Iron', 'Carbohydrate', 'Iodine'],
    correctIndex: 2,
    rationale: 'Macronutrients are carbohydrates, proteins, fats, and water. Vitamins and minerals are micronutrients.',
  },
  {
    id: 'intro-009',
    topic: 'intro',
    type: 'mcq',
    prompt: 'Approximately what percentage of body mass is water?',
    choices: ['30%', '45%', '60%', '75%'],
    correctIndex: 2,
    rationale: 'Water makes up roughly 60% of body mass and is essential for digestion, absorption, temperature regulation, and transport.',
  },
  {
    id: 'intro-010',
    topic: 'intro',
    type: 'mcq',
    prompt: 'Which of the following is a fat-soluble vitamin?',
    choices: ['Vitamin C', 'Vitamin B12', 'Vitamin D', 'Folate'],
    correctIndex: 2,
    rationale: 'Fat-soluble vitamins are A, D, E, and K. They dissolve in lipids and are stored in liver and fatty tissue.',
  },
  {
    id: 'intro-011',
    topic: 'intro',
    type: 'mcq',
    prompt: 'Which mineral is classified as a macromineral?',
    choices: ['Iron', 'Iodine', 'Calcium', 'Zinc'],
    correctIndex: 2,
    rationale: 'Macrominerals include calcium, magnesium, potassium, sodium, phosphorus, and sulfur. Iron, iodine, and zinc are trace minerals.',
  },
  {
    id: 'intro-012',
    topic: 'intro',
    type: 'mcq',
    prompt: 'Which of the following is a trace mineral?',
    choices: ['Sodium', 'Calcium', 'Magnesium', 'Iodine'],
    correctIndex: 3,
    rationale: 'Trace minerals (iron, zinc, iodine, selenium, copper, manganese, fluoride, chromium) are required in very small amounts.',
  },
  {
    id: 'intro-013',
    topic: 'intro',
    type: 'mcq',
    prompt: 'The BMI (Body Mass Index) formula is:',
    choices: [
      'Weight (kg) ÷ Height (m)²',
      'Weight (kg) × Height (m)²',
      'Weight (kg) ÷ Height (cm)',
      'Height (m)² ÷ Weight (kg)',
    ],
    correctIndex: 0,
    rationale: 'BMI = weight (kg) divided by height in meters squared. It is the most widely used population-level measure of adiposity.',
  },
  {
    id: 'intro-014',
    topic: 'intro',
    type: 'mcq',
    prompt: 'What does the abbreviation MUAC stand for?',
    choices: [
      'Mid-Upper Arm Circumference',
      'Maternal Underweight Anthropometric Code',
      'Measured Under Arm Composition',
      'Minimum Universal Anthropometric Cutoff',
    ],
    correctIndex: 0,
    rationale: 'MUAC = Mid-Upper Arm Circumference, used to screen for acute malnutrition, especially in children.',
  },
  {
    id: 'intro-015',
    topic: 'intro',
    type: 'mcq',
    prompt: 'Which indicator best reflects chronic or past growth failure?',
    choices: ['Wasting', 'Underweight', 'Stunting', 'Edema'],
    correctIndex: 2,
    rationale: 'Stunting (low height-for-age) reflects long-term cumulative nutritional deprivation.',
  },
  {
    id: 'intro-016',
    topic: 'intro',
    type: 'mcq',
    prompt: 'Which anthropometric indicator reflects short-term nutritional stress?',
    choices: ['Stunting', 'Wasting', 'MUAC (Mid-Upper Arm Circumference) alone', 'BMI (Body Mass Index)'],
    correctIndex: 1,
    rationale: 'Wasting (low weight-for-height) indicates recent, acute nutritional loss.',
  },
  {
    id: 'intro-017',
    topic: 'intro',
    type: 'mcq',
    prompt: 'A child with severe PEM (Protein-Energy Malnutrition), weight <60% of expected for age, frail thin wrinkled skin, drawn-in face and no edema most likely has:',
    choices: ['Kwashiorkor', 'Marasmus', 'Marasmic kwashiorkor', 'Stunting'],
    correctIndex: 1,
    rationale: 'Marasmus: severe growth failure with weight <60% expected, gross wasting, no edema.',
  },
  {
    id: 'intro-018',
    topic: 'intro',
    type: 'mcq',
    prompt: 'A child with severe PEM (Protein-Energy Malnutrition), weight 60–80% of expected, bilateral edema, dry flaky skin, hair changes and apathy most likely has:',
    choices: ['Marasmus', 'Kwashiorkor', 'Wasting only', 'Underweight'],
    correctIndex: 1,
    rationale: 'Kwashiorkor: severe protein deficiency with edema, skin and hair changes, and weight 60–80% of expected.',
  },
  {
    id: 'intro-019',
    topic: 'intro',
    type: 'mcq',
    prompt: 'The most serious form of PEM (Protein-Energy Malnutrition), combining features of both major presentations, is:',
    choices: ['Stunting', 'Wasting', 'Marasmic kwashiorkor', 'Iron deficiency'],
    correctIndex: 2,
    rationale: 'Marasmic kwashiorkor combines severe wasting with edema and carries the highest mortality.',
  },
  {
    id: 'intro-020',
    topic: 'intro',
    type: 'mcq',
    prompt: 'Which deficiency is the leading cause of preventable blindness in children under 5?',
    choices: ['Vitamin C', 'Vitamin A', 'Iron', 'Iodine'],
    correctIndex: 1,
    rationale: 'Vitamin A deficiency is the leading cause of childhood blindness worldwide.',
  },
  {
    id: 'intro-021',
    topic: 'intro',
    type: 'mcq',
    prompt: "Bitot's spots are a clinical sign of which deficiency?",
    choices: ['Iron', 'Iodine', 'Vitamin A', 'Vitamin D'],
    correctIndex: 2,
    rationale: "Bitot's spots are foamy keratinized lesions on the conjunctiva, classic for vitamin A deficiency.",
  },
  {
    id: 'intro-022',
    topic: 'intro',
    type: 'mcq',
    prompt: 'Goiter is associated with deficiency of which nutrient?',
    choices: ['Iron', 'Iodine', 'Vitamin A', 'Calcium'],
    correctIndex: 1,
    rationale: 'Goiter (enlarged thyroid) results from inadequate iodine intake, leading to thyroid hyperplasia.',
  },
  {
    id: 'intro-023',
    topic: 'intro',
    type: 'mcq',
    prompt: 'Maternal iodine deficiency during pregnancy can cause which condition in the child?',
    choices: ['Rickets', 'Cretinism', 'Scurvy', 'Marasmus'],
    correctIndex: 1,
    rationale: 'Iodine deficiency during pregnancy can cause cretinism — mental retardation and developmental problems in the child.',
  },
  {
    id: 'intro-024',
    topic: 'intro',
    type: 'tf',
    prompt: 'Health is defined only as the absence of disease.',
    correctAnswer: false,
    rationale: 'Health is a state of complete physical, mental, social, and spiritual well-being — not merely the absence of disease.',
  },
  {
    id: 'intro-025',
    topic: 'intro',
    type: 'tf',
    prompt: 'Vitamins do not provide energy to the body.',
    correctAnswer: true,
    rationale: 'Vitamins are non-energy yielding nutrients; they support biochemical processes but do not yield calories.',
  },

  // ============================================================
  // FACTORS INFLUENCING FOOD CONSUMPTION (15)
  // ============================================================
  {
    id: 'factors-001',
    topic: 'factors',
    type: 'mcq',
    prompt: 'Which of the following is NOT typically listed as a factor affecting food choice?',
    choices: ['Religion and culture', 'Cost of food', 'Blood type', 'Food preferences'],
    correctIndex: 2,
    rationale: 'Standard factors include individual needs, diet/health, religion/culture, cost, availability, preferences, and social/environmental context — blood type is not on this list.',
  },
  {
    id: 'factors-002',
    topic: 'factors',
    type: 'mcq',
    prompt: 'A patient with coeliac disease must avoid which substance?',
    choices: ['Lactose', 'Gluten', 'Casein', 'Fructose'],
    correctIndex: 1,
    rationale: 'Coeliac disease is an autoimmune reaction to gluten, found in wheat, rye, and barley.',
  },
  {
    id: 'factors-003',
    topic: 'factors',
    type: 'mcq',
    prompt: 'A patient with lactose intolerance is unable to digest:',
    choices: ['Wheat gluten', 'Milk sugar (lactose)', 'Egg whites', 'Soy protein'],
    correctIndex: 1,
    rationale: 'Lactose intolerance arises from reduced lactase enzyme activity, impairing digestion of milk sugar.',
  },
  {
    id: 'factors-004',
    topic: 'factors',
    type: 'mcq',
    prompt: 'Buying foods when they are in season generally results in:',
    choices: ['Higher prices', 'Lower prices', 'Lower nutritional value', 'Same price year-round'],
    correctIndex: 1,
    rationale: 'Seasonal foods are typically more abundant locally, lowering market price and often improving freshness.',
  },
  {
    id: 'factors-005',
    topic: 'factors',
    type: 'mcq',
    prompt: 'Which religion has specific dietary laws including avoidance of pork?',
    choices: ['Buddhism', 'Islam', 'Christianity', 'Hinduism'],
    correctIndex: 1,
    rationale: 'Islam prohibits pork consumption; Judaism also prohibits pork under kosher laws.',
  },
  {
    id: 'factors-006',
    topic: 'factors',
    type: 'mcq',
    prompt: 'Which religion traditionally avoids beef because cattle are considered sacred?',
    choices: ['Judaism', 'Islam', 'Hinduism', 'Rastafari Movement'],
    correctIndex: 2,
    rationale: 'Hinduism considers the cow sacred and avoids beef consumption.',
  },
  {
    id: 'factors-007',
    topic: 'factors',
    type: 'mcq',
    prompt: 'Which of the following is an example of an environmental/ethical food consideration?',
    choices: ['Personal hunger', 'Fair-trade certification', 'Family size', 'Time of day'],
    correctIndex: 1,
    rationale: 'Fair-trade certification ensures producers in less economically developed countries get fair payment, an ethical consideration.',
  },
  {
    id: 'factors-008',
    topic: 'factors',
    type: 'mcq',
    prompt: '"Free-range" labelling refers to:',
    choices: [
      'Animals fed only grain',
      'Animals allowed to roam freely outside',
      'Foods grown without irrigation',
      'Foods sold only at farmers markets',
    ],
    correctIndex: 1,
    rationale: 'Free-range means animals are allowed to roam outside; products often cost more than conventional alternatives.',
  },
  {
    id: 'factors-009',
    topic: 'factors',
    type: 'mcq',
    prompt: 'Which of the following must legally appear on the label of pre-packed food?',
    choices: [
      'Recipe instructions',
      'Carbon footprint',
      'List of ingredients including allergens',
      'Approval from a dietician',
    ],
    correctIndex: 2,
    rationale: 'Required label information includes name, ingredients (with allergens), weight/volume, dates, storage, manufacturer, and origin.',
  },
  {
    id: 'factors-010',
    topic: 'factors',
    type: 'mcq',
    prompt: 'Energy requirements vary based on all of the following EXCEPT:',
    choices: ['Age', 'Gender', 'Eye colour', 'Activity level'],
    correctIndex: 2,
    rationale: 'Energy needs depend on age, gender, body size, activity, and physiological state — not eye colour.',
  },
  {
    id: 'factors-011',
    topic: 'factors',
    type: 'mcq',
    prompt: 'Which best explains the rise in convenience food consumption?',
    choices: [
      'Larger households',
      'Lack of time and increased availability of labour-saving equipment',
      'Higher disposable income only',
      'Government subsidies',
    ],
    correctIndex: 1,
    rationale: 'Time-poor consumers with appliances like microwaves drive the growth of ready meals and convenience foods.',
  },
  {
    id: 'factors-012',
    topic: 'factors',
    type: 'mcq',
    prompt: 'Which group typically requires the highest daily energy intake?',
    choices: ['Sedentary adults', 'Older adults', 'Athletes', 'Toddlers'],
    correctIndex: 2,
    rationale: 'Athletes have the highest energy requirements because of high physical activity levels.',
  },
  {
    id: 'factors-013',
    topic: 'factors',
    type: 'tf',
    prompt: 'Genetically modified (GM) foods involve scientific intervention to alter the genes of a plant, animal, or micro-organism.',
    correctAnswer: true,
    rationale: 'GM foods are produced through targeted genetic modification or insertion of genes from another organism.',
  },
  {
    id: 'factors-014',
    topic: 'factors',
    type: 'tf',
    prompt: 'Food preferences are influenced only by taste, not by appearance or smell.',
    correctAnswer: false,
    rationale: 'Taste, odour, appearance, shape, and colour all shape food preferences.',
  },
  {
    id: 'factors-015',
    topic: 'factors',
    type: 'tf',
    prompt: 'Food prepared at home is often cheaper than equivalent take-away or ready-prepared meals.',
    correctAnswer: true,
    rationale: 'Home-prepared meals generally cost less than equivalent purchased prepared foods.',
  },

  // ============================================================
  // NUTRITION THROUGHOUT THE LIFECYCLE (25)
  // ============================================================
  {
    id: 'lifecycle-001',
    topic: 'lifecycle',
    type: 'mcq',
    prompt: 'How long before conception should women begin folic acid supplementation per WHO (World Health Organization)?',
    choices: ['1 week', 'At least 1 month before conception', '6 months', 'After conception is confirmed'],
    correctIndex: 1,
    rationale: 'WHO advises 400 µg folic acid daily starting at least 1 month before planned pregnancy, continuing through the first 12 weeks.',
  },
  {
    id: 'lifecycle-002',
    topic: 'lifecycle',
    type: 'mcq',
    prompt: 'The standard WHO (World Health Organization) daily folic acid dose for women planning pregnancy is:',
    choices: ['100 µg', '200 µg', '400 µg', '800 µg'],
    correctIndex: 2,
    rationale: '400 µg/day reduces the risk of neural tube defects in the developing fetus.',
  },
  {
    id: 'lifecycle-003',
    topic: 'lifecycle',
    type: 'mcq',
    prompt: 'A woman with a previously affected NTD (Neural Tube Defect) pregnancy should receive what daily folic acid dose before conception?',
    choices: ['400 µg', '1 mg', '5 mg', '10 mg'],
    correctIndex: 2,
    rationale: 'High-risk women take 5 mg of folic acid daily before conception and through early pregnancy.',
  },
  {
    id: 'lifecycle-004',
    topic: 'lifecycle',
    type: 'mcq',
    prompt: 'Folic acid supplementation primarily reduces the risk of which fetal defect?',
    choices: ['Cleft lip', 'Neural tube defects', 'Down syndrome', 'Cardiac septal defects'],
    correctIndex: 1,
    rationale: 'Folic acid prevents neural tube defects such as spina bifida and anencephaly.',
  },
  {
    id: 'lifecycle-005',
    topic: 'lifecycle',
    type: 'mcq',
    prompt: 'Maternal blood volume increases by approximately how much during pregnancy?',
    choices: ['10–20%', '25–30%', '40–50%', '70–80%'],
    correctIndex: 2,
    rationale: 'Maternal blood volume rises by ~40–50%, increasing iron requirements substantially.',
  },
  {
    id: 'lifecycle-006',
    topic: 'lifecycle',
    type: 'mcq',
    prompt: 'How many additional daily calories are typically recommended in the 2nd and 3rd trimesters?',
    choices: ['100–150', '280–300', '500–600', '900–1000'],
    correctIndex: 1,
    rationale: 'About 280–300 extra kcal/day support fetal growth in the later trimesters; focus is on nutrient quality.',
  },
  {
    id: 'lifecycle-007',
    topic: 'lifecycle',
    type: 'mcq',
    prompt: 'Pregnant women should avoid which type of fish due to mercury exposure risk?',
    choices: ['Sardines', 'Anchovies', 'Large predatory fish', 'Salmon'],
    correctIndex: 2,
    rationale: 'Large predatory fish (e.g., swordfish, king mackerel, shark) accumulate methylmercury and should be avoided.',
  },
  {
    id: 'lifecycle-008',
    topic: 'lifecycle',
    type: 'mcq',
    prompt: 'A breastfeeding mother typically needs how many additional kcal per day?',
    choices: ['100–200', '330–500', '800–1000', 'None'],
    correctIndex: 1,
    rationale: 'Lactating women need roughly 330–500 additional kcal/day to support milk synthesis.',
  },
  {
    id: 'lifecycle-009',
    topic: 'lifecycle',
    type: 'mcq',
    prompt: 'Which nutrient is critical for vegan or vegetarian breastfeeding mothers to supplement to protect the infant?',
    choices: ['Vitamin C', 'Vitamin B12', 'Vitamin E', 'Vitamin K'],
    correctIndex: 1,
    rationale: 'B12 is found mainly in animal products; deficiency in breastfed infants of vegan mothers can cause neurological damage.',
  },
  {
    id: 'lifecycle-010',
    topic: 'lifecycle',
    type: 'mcq',
    prompt: 'WHO (World Health Organization) recommends exclusive breastfeeding for how long?',
    choices: ['3 months', '6 months', '9 months', '12 months'],
    correctIndex: 1,
    rationale: 'Exclusive breastfeeding is recommended for the first 6 months; no water, juice, or solids unless medically advised.',
  },
  {
    id: 'lifecycle-011',
    topic: 'lifecycle',
    type: 'mcq',
    prompt: 'At what age should complementary feeding typically begin?',
    choices: ['3 months', '4 months', '6 months', '9 months'],
    correctIndex: 2,
    rationale: 'Complementary feeding begins at about 6 months, when infants are developmentally ready.',
  },
  {
    id: 'lifecycle-012',
    topic: 'lifecycle',
    type: 'mcq',
    prompt: 'Which food is strictly contraindicated in infants under 12 months?',
    choices: ['Mashed banana', 'Honey', 'Pureed sweet potato', 'Iron-fortified cereal'],
    correctIndex: 1,
    rationale: 'Honey may contain Clostridium botulinum spores that cause infant botulism. Never give honey under 12 months.',
  },
  {
    id: 'lifecycle-013',
    topic: 'lifecycle',
    type: 'mcq',
    prompt: 'Why is honey contraindicated in infants under 12 months?',
    choices: ['High sugar content', 'Allergy risk', 'Risk of infant botulism', 'Causes tooth decay only'],
    correctIndex: 2,
    rationale: 'Infant botulism: C. botulinum spores can colonize the immature infant gut and produce paralytic toxin.',
  },
  {
    id: 'lifecycle-014',
    topic: 'lifecycle',
    type: 'mcq',
    prompt: 'Infants typically double their birth weight by approximately what age?',
    choices: ['3 months', '6 months', '9 months', '12 months'],
    correctIndex: 1,
    rationale: 'Birth weight typically doubles by 6 months and triples by 1 year.',
  },
  {
    id: 'lifecycle-015',
    topic: 'lifecycle',
    type: 'mcq',
    prompt: "By 1 year, an infant's birth weight has typically:",
    choices: ['Doubled', 'Tripled', 'Quadrupled', 'Increased 10-fold'],
    correctIndex: 1,
    rationale: 'Birth weight triples by the first birthday in healthy infants.',
  },
  {
    id: 'lifecycle-016',
    topic: 'lifecycle',
    type: 'mcq',
    prompt: 'Which is recommended to be avoided as a main drink for infants under 12 months?',
    choices: ['Breastmilk', 'Formula', "Cow's milk", 'Oral rehydration solution when indicated'],
    correctIndex: 2,
    rationale: "Cow's milk lacks the nutrient balance needed and stresses immature kidneys before age 1.",
  },
  {
    id: 'lifecycle-017',
    topic: 'lifecycle',
    type: 'mcq',
    prompt: 'For adolescent girls aged 14–18, typical daily caloric needs are approximately:',
    choices: ['1,200–1,500', '1,800–2,400', '2,400–3,000', '3,000–3,500'],
    correctIndex: 1,
    rationale: 'Girls aged 14–18 typically require 1,800–2,400 kcal/day; boys 2,000–3,200 kcal/day.',
  },
  {
    id: 'lifecycle-018',
    topic: 'lifecycle',
    type: 'mcq',
    prompt: 'Carbohydrates should provide approximately what percentage of adolescent daily energy intake?',
    choices: ['10–20%', '25–35%', '45–65%', '70–85%'],
    correctIndex: 2,
    rationale: 'Adolescents should obtain 45–65% of energy from carbohydrates, ideally whole grains.',
  },
  {
    id: 'lifecycle-019',
    topic: 'lifecycle',
    type: 'mcq',
    prompt: 'An average adult woman needs approximately how many kcal/day to maintain her weight?',
    choices: ['1,200', '1,500', '2,000', '2,500'],
    correctIndex: 2,
    rationale: 'About 2,000 kcal/day for maintenance; ~1,500 kcal/day for ~0.5–1 kg/week weight loss.',
  },
  {
    id: 'lifecycle-020',
    topic: 'lifecycle',
    type: 'mcq',
    prompt: 'Recommended adult fluid intake is approximately:',
    choices: ['0.5–1 L', '1–2 L', '2–3 L', '4–5 L'],
    correctIndex: 2,
    rationale: 'Adults should consume roughly 2–3 L of fluid daily, primarily as water.',
  },
  {
    id: 'lifecycle-021',
    topic: 'lifecycle',
    type: 'mcq',
    prompt: 'The age-related loss of muscle mass that is a primary nutritional concern in older adults is termed:',
    choices: ['Cachexia', 'Sarcopenia', 'Atrophy', 'Frailty syndrome'],
    correctIndex: 1,
    rationale: 'Sarcopenia is the progressive loss of skeletal muscle with aging — adequate protein intake is key to prevention.',
  },
  {
    id: 'lifecycle-022',
    topic: 'lifecycle',
    type: 'mcq',
    prompt: 'Why is dehydration risk increased in older adults?',
    choices: [
      'Increased sweating',
      'Diminished thirst sensation',
      'Higher metabolism',
      'Increased renal concentrating ability',
    ],
    correctIndex: 1,
    rationale: 'Thirst sensation declines with age, so older adults may not feel thirsty even when fluid-deficient.',
  },
  {
    id: 'lifecycle-023',
    topic: 'lifecycle',
    type: 'mcq',
    prompt: 'Vitamin B12 absorption may decline in older adults primarily because of:',
    choices: ['Increased stomach acid', 'Decreased stomach acid', 'Increased intrinsic factor', 'Higher dietary intake'],
    correctIndex: 1,
    rationale: 'Lower gastric acid in aging impairs cleavage of food-bound B12 and its absorption.',
  },
  {
    id: 'lifecycle-024',
    topic: 'lifecycle',
    type: 'tf',
    prompt: 'Pregnant women should "eat for two" by doubling their calorie intake.',
    correctAnswer: false,
    rationale: 'Focus is on nutrient quality, not doubling calories. Only ~280–300 extra kcal/day are needed in later trimesters.',
  },
  {
    id: 'lifecycle-025',
    topic: 'lifecycle',
    type: 'tf',
    prompt: 'Calcium content of breastmilk remains stable regardless of maternal intake, but inadequate intake depletes maternal stores.',
    correctAnswer: true,
    rationale: 'Breastmilk calcium is preserved at the expense of maternal bone density when intake is low.',
  },

  // ============================================================
  // MALNUTRITION: TYPES, CAUSES, CONSEQUENCES (20)
  // ============================================================
  {
    id: 'mal-001',
    topic: 'malnutrition',
    type: 'mcq',
    prompt: 'Malnutrition is best defined as:',
    choices: [
      'Lack of food only',
      'A condition resulting from deficiency, excess, or imbalance of nutrients',
      'Severe weight loss only',
      'A vitamin deficiency disease',
    ],
    correctIndex: 1,
    rationale: 'Malnutrition encompasses deficiencies, excesses, and imbalances affecting growth, health, and development.',
  },
  {
    id: 'mal-002',
    topic: 'malnutrition',
    type: 'mcq',
    prompt: 'Malnutrition is broadly divided into:',
    choices: [
      'Acute and chronic',
      'Undernutrition and overnutrition',
      'Primary and secondary',
      'Reversible and irreversible',
    ],
    correctIndex: 1,
    rationale: 'The two broad categories are undernutrition and overnutrition.',
  },
  {
    id: 'mal-003',
    topic: 'malnutrition',
    type: 'mcq',
    prompt: '"Stunting" refers to:',
    choices: ['Low height for age', 'Low weight for height', 'Low weight for age', 'Low MUAC (Mid-Upper Arm Circumference)'],
    correctIndex: 0,
    rationale: 'Stunting = low height-for-age, indicating chronic malnutrition.',
  },
  {
    id: 'mal-004',
    topic: 'malnutrition',
    type: 'mcq',
    prompt: '"Wasting" refers to:',
    choices: ['Low height for age', 'Low weight for height', 'Low weight for age', 'Edema only'],
    correctIndex: 1,
    rationale: 'Wasting = low weight-for-height, indicating acute malnutrition.',
  },
  {
    id: 'mal-005',
    topic: 'malnutrition',
    type: 'mcq',
    prompt: '"Underweight" is defined as:',
    choices: ['Low height for age', 'Low weight for height', 'Low weight for age', 'BMI (Body Mass Index) < 16'],
    correctIndex: 2,
    rationale: 'Underweight = low weight-for-age — a composite of stunting and wasting.',
  },
  {
    id: 'mal-006',
    topic: 'malnutrition',
    type: 'mcq',
    prompt: 'In the UNICEF framework, which is an IMMEDIATE cause of malnutrition?',
    choices: ['Poverty', 'Inadequate dietary intake', 'Low maternal education', 'Drought'],
    correctIndex: 1,
    rationale: 'Immediate causes act at the individual level: inadequate dietary intake and disease.',
  },
  {
    id: 'mal-007',
    topic: 'malnutrition',
    type: 'mcq',
    prompt: 'Which is an UNDERLYING (household/community-level) cause of malnutrition?',
    choices: ['Disease', 'Household food insecurity', 'Poverty', 'Inadequate dietary intake'],
    correctIndex: 1,
    rationale: 'Underlying causes include food insecurity, poor childcare, inadequate services, and poor WASH (Water, Sanitation, and Hygiene).',
  },
  {
    id: 'mal-008',
    topic: 'malnutrition',
    type: 'mcq',
    prompt: 'Which is a BASIC (societal-level) cause of malnutrition?',
    choices: ['Diarrhea', 'Poor WASH (Water, Sanitation, and Hygiene)', 'Poverty', 'Inadequate dietary intake'],
    correctIndex: 2,
    rationale: 'Basic causes are societal: poverty, low education, political/economic instability, cultural practices.',
  },
  {
    id: 'mal-009',
    topic: 'malnutrition',
    type: 'mcq',
    prompt: 'The malnutrition–infection cycle describes:',
    choices: [
      'Infection causing weight gain',
      'Poor nutrition weakens immunity, leading to infection, which worsens nutritional status',
      'Vaccine-preventable diseases only',
      'A single episode of illness',
    ],
    correctIndex: 1,
    rationale: 'A vicious cycle: malnutrition compromises immunity, infection causes nutrient loss and poor appetite, worsening malnutrition.',
  },
  {
    id: 'mal-010',
    topic: 'malnutrition',
    type: 'mcq',
    prompt: 'Approximately what percentage of child mortality in Ghana is linked to malnutrition?',
    choices: ['5%', '10%', 'Up to 24%', '50%'],
    correctIndex: 2,
    rationale: 'Up to 24% of child deaths in Ghana are linked to malnutrition.',
  },
  {
    id: 'mal-011',
    topic: 'malnutrition',
    type: 'mcq',
    prompt: 'The approximate annual economic cost of malnutrition to Ghana is:',
    choices: ['1% of GDP', '6% of GDP', '15% of GDP', '25% of GDP'],
    correctIndex: 1,
    rationale: 'Malnutrition costs Ghana up to ~6% of GDP annually.',
  },
  {
    id: 'mal-012',
    topic: 'malnutrition',
    type: 'mcq',
    prompt: 'Approximately what percentage of Ghanaian children under 5 are stunted?',
    choices: ['5–7%', '12%', '17–18%', '35%'],
    correctIndex: 2,
    rationale: 'About 17–18% of children under 5 in Ghana are stunted.',
  },
  {
    id: 'mal-013',
    topic: 'malnutrition',
    type: 'mcq',
    prompt: 'Approximately what percentage of Ghanaian women are anemic?',
    choices: ['10%', '25%', '42%', '60%'],
    correctIndex: 2,
    rationale: 'Roughly 42% of women in Ghana are affected by anemia.',
  },
  {
    id: 'mal-014',
    topic: 'malnutrition',
    type: 'mcq',
    prompt: 'The "double burden of malnutrition" refers to:',
    choices: [
      'Two children malnourished in one family',
      'Coexistence of undernutrition and overnutrition in the same population',
      'Stunting plus wasting only',
      'Marasmic kwashiorkor',
    ],
    correctIndex: 1,
    rationale: 'Many low- and middle-income countries, including Ghana, face both undernutrition and rising overnutrition simultaneously.',
  },
  {
    id: 'mal-015',
    topic: 'malnutrition',
    type: 'mcq',
    prompt: 'Which consequence of malnutrition is considered intergenerational?',
    choices: [
      'Reduced school performance',
      'Low birth weight infants born to malnourished mothers',
      'Increased infection rates',
      'Weak immunity',
    ],
    correctIndex: 1,
    rationale: 'Malnourished mothers tend to deliver low birth weight infants, perpetuating the cycle.',
  },
  {
    id: 'mal-016',
    topic: 'malnutrition',
    type: 'mcq',
    prompt: 'The UNICEF conceptual framework arranges causes of malnutrition:',
    choices: [
      'Randomly',
      'Hierarchically from society → household → individual',
      'Only at household level',
      'Only by age group',
    ],
    correctIndex: 1,
    rationale: 'The framework shows a hierarchical relationship across society, household/community, and individual levels.',
  },
  {
    id: 'mal-017',
    topic: 'malnutrition',
    type: 'mcq',
    prompt: 'Which best describes Ghana child-nutrition inequalities?',
    choices: [
      'Worse in cities than rural areas',
      'Worse in rural areas, poor households, and among less-educated mothers',
      'Distributed evenly nationwide',
      'Worse only in coastal regions',
    ],
    correctIndex: 1,
    rationale: 'Malnutrition disproportionately affects rural, poor, and less-educated households.',
  },
  {
    id: 'mal-018',
    topic: 'malnutrition',
    type: 'tf',
    prompt: 'Overnutrition refers only to consuming too many calories.',
    correctAnswer: false,
    rationale: 'Overnutrition is excess intake of nutrients (especially energy), leading to overweight, obesity, and diet-related NCDs — broader than calories alone.',
  },
  {
    id: 'mal-019',
    topic: 'malnutrition',
    type: 'tf',
    prompt: 'Malnutrition affects only physical growth and not cognitive function.',
    correctAnswer: false,
    rationale: 'Malnutrition impairs brain development, learning, and school performance, in addition to physical growth.',
  },
  {
    id: 'mal-020',
    topic: 'malnutrition',
    type: 'tf',
    prompt: 'Diet-related NCDs like diabetes and hypertension are considered forms of overnutrition.',
    correctAnswer: true,
    rationale: 'Overnutrition forms include overweight, obesity, and diet-related NCDs such as diabetes and hypertension.',
  },

  // ============================================================
  // UNDERNUTRITION (25)
  // ============================================================
  {
    id: 'undern-001',
    topic: 'undernutrition',
    type: 'mcq',
    prompt: 'A child with bilateral pitting edema, swollen abdomen, hair discoloration, and apathy most likely has:',
    choices: ['Marasmus', 'Kwashiorkor', 'Stunting', 'Vitamin A deficiency'],
    correctIndex: 1,
    rationale: 'Kwashiorkor: severe protein deficiency with edema, hair changes, skin lesions, and apathy.',
  },
  {
    id: 'undern-002',
    topic: 'undernutrition',
    type: 'mcq',
    prompt: 'The "flag sign" in kwashiorkor refers to:',
    choices: ['Skin lesions', 'Bands of hair discoloration', 'Abdominal distention', 'Edema'],
    correctIndex: 1,
    rationale: 'The flag sign is alternating bands of normal and depigmented hair reflecting episodes of protein deficiency.',
  },
  {
    id: 'undern-003',
    topic: 'undernutrition',
    type: 'mcq',
    prompt: '"Flaky paint dermatosis" is a classical sign of:',
    choices: ['Marasmus', 'Kwashiorkor', 'Iron deficiency', 'Vitamin A deficiency'],
    correctIndex: 1,
    rationale: 'Flaky-paint dermatosis — peeling pigmented skin patches — is a hallmark of kwashiorkor.',
  },
  {
    id: 'undern-004',
    topic: 'undernutrition',
    type: 'mcq',
    prompt: 'A severely wasted child with "old man" facial appearance and no edema most likely has:',
    choices: ['Kwashiorkor', 'Marasmus', 'Stunting', 'Underweight only'],
    correctIndex: 1,
    rationale: 'Marasmus: severe wasting, loss of subcutaneous fat, drawn-in face — no edema.',
  },
  {
    id: 'undern-005',
    topic: 'undernutrition',
    type: 'mcq',
    prompt: 'Marasmus is caused primarily by:',
    choices: [
      'Protein deficiency with adequate energy',
      'Severe deficiency of both energy and protein',
      'Iron deficiency',
      'Vitamin A deficiency',
    ],
    correctIndex: 1,
    rationale: 'Marasmus results from severe combined energy and protein deficiency.',
  },
  {
    id: 'undern-006',
    topic: 'undernutrition',
    type: 'mcq',
    prompt: 'Kwashiorkor is caused primarily by:',
    choices: [
      'Severe protein deficiency with adequate or near-adequate energy',
      'Severe energy deficiency only',
      'Vitamin C deficiency',
      'Iodine deficiency',
    ],
    correctIndex: 0,
    rationale: 'Kwashiorkor: severe protein deficiency with near-adequate calorie intake; classically triggered by early weaning.',
  },
  {
    id: 'undern-007',
    topic: 'undernutrition',
    type: 'mcq',
    prompt: 'Which therapeutic feed is used FIRST in inpatient management of severe malnutrition?',
    choices: ['F-100', 'F-75', 'RUTF (Ready-to-Use Therapeutic Food)', 'High-protein porridge'],
    correctIndex: 1,
    rationale: 'F-75 (~75 kcal/100 mL) is used in the stabilization phase to restore metabolic balance.',
  },
  {
    id: 'undern-008',
    topic: 'undernutrition',
    type: 'mcq',
    prompt: 'A classical sign of vitamin A deficiency is:',
    choices: ['Pallor', 'Goiter', 'Night blindness', 'Edema'],
    correctIndex: 2,
    rationale: 'Night blindness is one of the earliest signs of vitamin A deficiency.',
  },
  {
    id: 'undern-009',
    topic: 'undernutrition',
    type: 'mcq',
    prompt: 'Xerophthalmia refers to:',
    choices: ['Cataracts', 'Drying of the eye from vitamin A deficiency', 'Conjunctivitis', 'Color blindness'],
    correctIndex: 1,
    rationale: 'Xerophthalmia is the drying of the conjunctiva and cornea from vitamin A deficiency.',
  },
  {
    id: 'undern-010',
    topic: 'undernutrition',
    type: 'mcq',
    prompt: "Bitot's spots are seen in deficiency of:",
    choices: ['Iron', 'Iodine', 'Vitamin A', 'Vitamin D'],
    correctIndex: 2,
    rationale: "Bitot's spots are foamy keratin patches on the conjunctiva — classic for vitamin A deficiency.",
  },
  {
    id: 'undern-011',
    topic: 'undernutrition',
    type: 'mcq',
    prompt: 'A common sign of iron deficiency anemia is:',
    choices: ['Edema', 'Pallor and fatigue', 'Goiter', 'Night blindness'],
    correctIndex: 1,
    rationale: 'Iron deficiency anemia presents with pallor, fatigue, shortness of breath, and poor concentration.',
  },
  {
    id: 'undern-012',
    topic: 'undernutrition',
    type: 'mcq',
    prompt: 'Common causes of iron deficiency anemia include:',
    choices: [
      'Excess iron supplementation',
      'Poor dietary intake and blood loss',
      'Vitamin C excess',
      'Iodine deficiency',
    ],
    correctIndex: 1,
    rationale: 'Causes: low dietary intake, blood loss (menstruation, parasites), and impaired absorption.',
  },
  {
    id: 'undern-013',
    topic: 'undernutrition',
    type: 'mcq',
    prompt: 'Universal salt iodization primarily prevents:',
    choices: ['Anemia', 'Goiter and IQ (Intelligence Quotient) deficits', 'Rickets', 'Marasmus'],
    correctIndex: 1,
    rationale: 'Iodized salt prevents goiter, hypothyroidism, and cognitive impairment.',
  },
  {
    id: 'undern-014',
    topic: 'undernutrition',
    type: 'mcq',
    prompt: 'Cretinism results from iodine deficiency occurring during which stage?',
    choices: ['Adolescence', 'Pregnancy (maternal deficiency)', 'Old age', 'Infancy after weaning'],
    correctIndex: 1,
    rationale: 'Maternal iodine deficiency in pregnancy causes cretinism in the offspring — severe mental and physical impairment.',
  },
  {
    id: 'undern-015',
    topic: 'undernutrition',
    type: 'mcq',
    prompt: 'Stunting is best described as:',
    choices: [
      'Acute malnutrition',
      'Chronic malnutrition with largely irreversible deficits if untreated early',
      'Short-term weight loss',
      'A purely micronutrient disorder',
    ],
    correctIndex: 1,
    rationale: 'Stunting reflects chronic deprivation; growth deficits beyond a critical window are largely irreversible.',
  },
  {
    id: 'undern-016',
    topic: 'undernutrition',
    type: 'mcq',
    prompt: 'Which is NOT typically a clinical sign of undernutrition?',
    choices: ['Hair thinning', 'Hypertension', 'Muscle wasting', 'Delayed wound healing'],
    correctIndex: 1,
    rationale: 'Undernutrition typically lowers blood pressure and impairs immunity, growth, and healing — hypertension is an overnutrition-related finding.',
  },
  {
    id: 'undern-017',
    topic: 'undernutrition',
    type: 'mcq',
    prompt: 'Behavioral/cognitive signs of undernutrition include:',
    choices: ['Hyperactivity', 'Irritability and poor concentration', 'Increased appetite', 'Aggression only'],
    correctIndex: 1,
    rationale: 'Common behavioural/cognitive findings: irritability, apathy, poor concentration, and delayed mental development.',
  },
  {
    id: 'undern-018',
    topic: 'undernutrition',
    type: 'mcq',
    prompt: 'A key prevention strategy for undernutrition in infants is:',
    choices: [
      'Antibiotic prophylaxis for all children',
      'Exclusive breastfeeding for the first 6 months',
      'High-protein diets from 3 months',
      'Limiting all fats',
    ],
    correctIndex: 1,
    rationale: 'Exclusive breastfeeding for 6 months, followed by appropriate complementary feeding, is foundational to preventing undernutrition.',
  },
  {
    id: 'undern-019',
    topic: 'undernutrition',
    type: 'mcq',
    prompt: 'Which is part of MEDICAL management of undernutrition?',
    choices: [
      'Surgical resection',
      'Treatment of infections (antibiotics, antimalarials, deworming)',
      'Antihypertensives',
      'Insulin therapy',
    ],
    correctIndex: 1,
    rationale: 'Medical management targets infections and complications such as dehydration alongside nutritional rehabilitation.',
  },
  {
    id: 'undern-020',
    topic: 'undernutrition',
    type: 'mcq',
    prompt: 'Which best describes marasmic kwashiorkor?',
    choices: ['Edema only', 'Severe wasting plus edema', 'Goiter plus anemia', 'Stunting plus underweight'],
    correctIndex: 1,
    rationale: 'Marasmic kwashiorkor combines severe wasting with edema — the most serious PEM (Protein-Energy Malnutrition) presentation.',
  },
  {
    id: 'undern-021',
    topic: 'undernutrition',
    type: 'mcq',
    prompt: 'Which is NOT typically a sign of stunting?',
    choices: [
      'Short stature for age',
      'Delayed cognitive development',
      'Bilateral pitting edema',
      'Poor school performance',
    ],
    correctIndex: 2,
    rationale: 'Bilateral pitting edema is a hallmark of kwashiorkor, not stunting.',
  },
  {
    id: 'undern-022',
    topic: 'undernutrition',
    type: 'mcq',
    prompt: 'Which dietary advice best helps prevent iron deficiency anemia?',
    choices: [
      'Drink tea or coffee with meals',
      'Include vitamin C-rich foods with iron sources',
      'Avoid red meat',
      'Take iron supplements only when symptomatic',
    ],
    correctIndex: 1,
    rationale: 'Vitamin C enhances non-heme iron absorption; tea/coffee with meals inhibits it.',
  },
  {
    id: 'undern-023',
    topic: 'undernutrition',
    type: 'tf',
    prompt: 'Stunting is fully reversible if nutrition is improved after age 5.',
    correctAnswer: false,
    rationale: 'Most growth and cognitive deficits from stunting become largely irreversible once the early window has passed.',
  },
  {
    id: 'undern-024',
    topic: 'undernutrition',
    type: 'tf',
    prompt: 'Zinc supplementation is recommended as part of childhood diarrhea management.',
    correctAnswer: true,
    rationale: 'Zinc reduces diarrhea duration, severity, and recurrence; given with ORT (Oral Rehydration Therapy).',
  },
  {
    id: 'undern-025',
    topic: 'undernutrition',
    type: 'tf',
    prompt: 'Iron deficiency anemia reduces both work capacity and cognitive performance.',
    correctAnswer: true,
    rationale: 'Anemia impairs oxygen delivery, lowering productivity and cognitive function.',
  },

  // ============================================================
  // SAM MANAGEMENT (20)
  // ============================================================
  {
    id: 'sam-001',
    topic: 'sam',
    type: 'mcq',
    prompt: 'Which MUAC (Mid-Upper Arm Circumference) cutoff defines severe acute malnutrition in children?',
    choices: ['<11.5 mm', '<12.5 mm', '<13.5 mm', '<14.0 mm'],
    correctIndex: 0,
    rationale: 'MUAC <115 mm (11.5 cm) defines SAM (Severe Acute Malnutrition) in children 6–59 months.',
  },
  {
    id: 'sam-002',
    topic: 'sam',
    type: 'mcq',
    prompt: 'Which weight-for-height/length Z-score defines SAM (Severe Acute Malnutrition)?',
    choices: ['< −1 SD', '< −2 SD', '< −3 SD', '< −4 SD'],
    correctIndex: 2,
    rationale: 'WHZ (Weight-for-Height Z-score) < −3 SD indicates severe acute malnutrition.',
  },
  {
    id: 'sam-003',
    topic: 'sam',
    type: 'mcq',
    prompt: 'Which finding ALONE qualifies a child for SAM (Severe Acute Malnutrition) diagnosis regardless of weight measurements?',
    choices: ['Poor appetite', 'Bilateral pitting edema', 'Cough', 'Fever'],
    correctIndex: 1,
    rationale: 'Bilateral pitting edema, especially ++ or +++, is itself diagnostic of SAM.',
  },
  {
    id: 'sam-004',
    topic: 'sam',
    type: 'mcq',
    prompt: 'All infants under 6 months with SAM (Severe Acute Malnutrition) should be managed:',
    choices: [
      'Outpatient with RUTF (Ready-to-Use Therapeutic Food)',
      'Inpatient',
      'At home with breastfeeding only',
      'Only if MUAC (Mid-Upper Arm Circumference) <11.5 mm',
    ],
    correctIndex: 1,
    rationale: 'Infants <6 months with SAM need inpatient care due to breastfeeding and medical needs.',
  },
  {
    id: 'sam-005',
    topic: 'sam',
    type: 'mcq',
    prompt: 'The therapeutic feed used in the stabilization phase is:',
    choices: ['F-100', 'F-75', 'RUTF (Ready-to-Use Therapeutic Food)', 'Whole milk'],
    correctIndex: 1,
    rationale: 'F-75 is low-energy, easy to digest, used to restore metabolic balance.',
  },
  {
    id: 'sam-006',
    topic: 'sam',
    type: 'mcq',
    prompt: 'F-75 milk provides approximately how many kcal per 100 mL?',
    choices: ['50', '75', '100', '150'],
    correctIndex: 1,
    rationale: 'F-75 supplies ~75 kcal per 100 mL.',
  },
  {
    id: 'sam-007',
    topic: 'sam',
    type: 'mcq',
    prompt: 'Once medically stable, the child transitions to which feed for catch-up growth?',
    choices: ['F-75 only', 'F-100 or RUTF (Ready-to-Use Therapeutic Food)', 'Skim milk', 'High-fat oils'],
    correctIndex: 1,
    rationale: 'Rehabilitation phase uses F-100 or RUTF to provide high energy and protein for catch-up.',
  },
  {
    id: 'sam-008',
    topic: 'sam',
    type: 'mcq',
    prompt: 'A major complication of overly aggressive refeeding in SAM (Severe Acute Malnutrition) is:',
    choices: ['Hypertension', 'Refeeding syndrome', 'Goiter', 'Dental caries'],
    correctIndex: 1,
    rationale: 'Refeeding syndrome — life-threatening shifts in electrolytes and fluid balance — must be prevented by gradual feeding.',
  },
  {
    id: 'sam-009',
    topic: 'sam',
    type: 'mcq',
    prompt: 'Which is NOT a routine medical intervention on admission for SAM (Severe Acute Malnutrition)?',
    choices: [
      'Broad-spectrum antibiotics',
      'Vitamin A supplementation',
      'High-dose insulin',
      'Treatment for malaria where endemic',
    ],
    correctIndex: 2,
    rationale: 'Routine SAM admission includes antibiotics, malaria treatment, vitamin A, deworming, and HIV/TB screening — not insulin.',
  },
  {
    id: 'sam-010',
    topic: 'sam',
    type: 'mcq',
    prompt: 'Why is aggressive IV fluid resuscitation generally AVOIDED in SAM (Severe Acute Malnutrition)?',
    choices: [
      'Risk of fluid overload due to compromised cardiac and renal function',
      'Causes hyperkalemia only',
      'Painful for the child',
      'Causes vitamin A loss',
    ],
    correctIndex: 0,
    rationale: 'SAM children have fragile physiology and high risk of fluid overload; IV fluids are used cautiously.',
  },
  {
    id: 'sam-011',
    topic: 'sam',
    type: 'mcq',
    prompt: 'The recommended ambient temperature for an SAM (Severe Acute Malnutrition) child is:',
    choices: ['18–22 °C', '25–30 °C', '32–35 °C', '15–18 °C'],
    correctIndex: 1,
    rationale: 'Keep child warm at 25–30 °C with no drafts to prevent hypothermia.',
  },
  {
    id: 'sam-012',
    topic: 'sam',
    type: 'mcq',
    prompt: 'The appetite test is used in SAM (Severe Acute Malnutrition) care to:',
    choices: [
      'Diagnose anemia',
      'Decide between inpatient and outpatient management',
      'Test for kwashiorkor',
      'Measure thyroid function',
    ],
    correctIndex: 1,
    rationale: 'A failed appetite test indicates need for inpatient care; passing it supports outpatient RUTF (Ready-to-Use Therapeutic Food) management.',
  },
  {
    id: 'sam-013',
    topic: 'sam',
    type: 'mcq',
    prompt: 'A discharge criterion for a child recovering from SAM (Severe Acute Malnutrition) includes:',
    choices: ['MUAC (Mid-Upper Arm Circumference) ≥12.5 mm', 'MUAC ≥10 mm', 'Persistent edema', 'WHZ (Weight-for-Height Z-score) < −3 SD'],
    correctIndex: 0,
    rationale: 'Final discharge requires MUAC ≥125 mm (12.5 cm) or WHZ ≥ −2 SD, plus clinical wellness and no edema for ≥2 weeks.',
  },
  {
    id: 'sam-014',
    topic: 'sam',
    type: 'mcq',
    prompt: 'A child should have no edema for at least how long before final discharge from SAM (Severe Acute Malnutrition) treatment?',
    choices: ['3 days', '1 week', '2 weeks', '6 weeks'],
    correctIndex: 2,
    rationale: 'Edema must be absent for ≥2 weeks before final discharge.',
  },
  {
    id: 'sam-015',
    topic: 'sam',
    type: 'mcq',
    prompt: 'The principle "stabilize first, then catch-up feeding" reflects:',
    choices: [
      'Outpatient-only management',
      'Avoidance of refeeding complications and prioritizing life-saving treatment',
      'Antibiotic stewardship',
      'Cost reduction strategy',
    ],
    correctIndex: 1,
    rationale: 'Life-threatening problems are addressed first; aggressive feeding is delayed to avoid refeeding syndrome.',
  },
  {
    id: 'sam-016',
    topic: 'sam',
    type: 'mcq',
    prompt: 'The transition phase between F-75 and F-100/RUTF (Ready-to-Use Therapeutic Food) typically lasts:',
    choices: ['<1 day', '1–3 days', '1 week', '2 weeks'],
    correctIndex: 1,
    rationale: 'Transition typically lasts 1–3 days as energy intake is gradually increased.',
  },
  {
    id: 'sam-017',
    topic: 'sam',
    type: 'mcq',
    prompt: 'During the stabilization phase, F-75 is best given:',
    choices: ['Once daily', 'Frequent small feeds (initially hourly)', 'Only on demand', 'IV only'],
    correctIndex: 1,
    rationale: 'Small, frequent feeds prevent hypoglycemia and avoid overwhelming compromised metabolism.',
  },
  {
    id: 'sam-018',
    topic: 'sam',
    type: 'tf',
    prompt: 'RUTF (Ready-to-Use Therapeutic Food) is intended for SAM (Severe Acute Malnutrition) children WITHOUT medical complications.',
    correctAnswer: true,
    rationale: 'Under the CMAM (Community-based Management of Acute Malnutrition) model, RUTF is used for SAM without complications, often outpatient.',
  },
  {
    id: 'sam-019',
    topic: 'sam',
    type: 'tf',
    prompt: 'Caregivers should be excluded from feeding to ensure clinical precision.',
    correctAnswer: false,
    rationale: 'Caregiver involvement is a core SAM (Severe Acute Malnutrition) care principle; it improves outcomes and prepares for outpatient continuation.',
  },
  {
    id: 'sam-020',
    topic: 'sam',
    type: 'tf',
    prompt: 'Hypoglycemia and hypothermia are common preventable causes of death in untreated SAM (Severe Acute Malnutrition) children.',
    correctAnswer: true,
    rationale: 'Hypoglycemia, hypothermia, infection, and dehydration are the chief killers of untreated SAM children.',
  },

  // ============================================================
  // OVERNUTRITION & DIET-RELATED NCDs (25)
  // ============================================================
  {
    id: 'ncd-001',
    topic: 'ncd',
    type: 'mcq',
    prompt: 'BMI (Body Mass Index) is calculated as:',
    choices: [
      'Weight (lbs) / Height (in)',
      'Weight (kg) / Height² (m²)',
      'Weight (kg) × Height (m)',
      'Height (m) / Weight (kg)',
    ],
    correctIndex: 1,
    rationale: 'BMI = weight in kg divided by height in meters squared.',
  },
  {
    id: 'ncd-002',
    topic: 'ncd',
    type: 'mcq',
    prompt: 'The Acceptable Macronutrient Distribution Range (AMDR (Acceptable Macronutrient Distribution Range)) for carbohydrate is:',
    choices: ['10–35%', '20–35%', '45–65%', '70–85%'],
    correctIndex: 2,
    rationale: 'Carbohydrate AMDR is 45–65% of total kcal.',
  },
  {
    id: 'ncd-003',
    topic: 'ncd',
    type: 'mcq',
    prompt: 'The AMDR (Acceptable Macronutrient Distribution Range) for protein is:',
    choices: ['10–35%', '20–35%', '45–65%', '5–10%'],
    correctIndex: 0,
    rationale: 'Protein AMDR is 10–35% of total kcal.',
  },
  {
    id: 'ncd-004',
    topic: 'ncd',
    type: 'mcq',
    prompt: 'The AMDR (Acceptable Macronutrient Distribution Range) for fat is:',
    choices: ['10–20%', '20–35%', '35–50%', '5–15%'],
    correctIndex: 1,
    rationale: 'Fat AMDR is 20–35% of total kcal.',
  },
  {
    id: 'ncd-005',
    topic: 'ncd',
    type: 'mcq',
    prompt: 'For sustainable weight loss, the recommended daily caloric deficit is approximately:',
    choices: ['100–200 kcal', '500–1000 kcal', '1500–2000 kcal', '2000–2500 kcal'],
    correctIndex: 1,
    rationale: 'A daily deficit of 500–1000 kcal supports gradual weight loss of ~0.5–1 kg/week.',
  },
  {
    id: 'ncd-006',
    topic: 'ncd',
    type: 'mcq',
    prompt: 'A 500–1000 kcal/day deficit corresponds to approximately what weight loss per week?',
    choices: ['0.1–0.2 kg', '0.5–1 kg', '2–3 kg', '4–5 kg'],
    correctIndex: 1,
    rationale: 'Roughly 0.5–1 kg per week — the recommended sustainable rate.',
  },
  {
    id: 'ncd-007',
    topic: 'ncd',
    type: 'mcq',
    prompt: 'Recommended minimum physical activity for adults is:',
    choices: [
      'At least 5 days/week for 30 minutes of moderate activity',
      'Daily for 60 minutes',
      '2 days/week for 90 minutes',
      'Only during attempts at weight loss',
    ],
    correctIndex: 0,
    rationale: 'Exercise should occur most days (≥5/week) for at least 30 minutes, starting slowly and increasing intensity.',
  },
  {
    id: 'ncd-008',
    topic: 'ncd',
    type: 'mcq',
    prompt: 'Hypertension is defined as a consistent blood pressure of:',
    choices: ['120/80 mmHg or higher', '130/85 mmHg or higher', '140/90 mmHg or higher', '160/100 mmHg or higher'],
    correctIndex: 2,
    rationale: 'A consistent BP (Blood Pressure) ≥140/90 mmHg is classified as high blood pressure (hypertension).',
  },
  {
    id: 'ncd-009',
    topic: 'ncd',
    type: 'mcq',
    prompt: 'Hypertension is commonly called the "silent killer" because:',
    choices: [
      'Diagnosis is difficult',
      'It usually has no warning signs or symptoms',
      'It rapidly causes death without warning',
      'Treatment is unavailable',
    ],
    correctIndex: 1,
    rationale: 'Most people with hypertension have no symptoms, so it can damage organs unnoticed.',
  },
  {
    id: 'ncd-010',
    topic: 'ncd',
    type: 'mcq',
    prompt: 'The DASH (Dietary Approaches to Stop Hypertension) diet emphasizes which food pattern?',
    choices: [
      'High protein, very low carbohydrate',
      'Fruits, vegetables, low-fat dairy, whole grains, lean protein',
      'Ketogenic foods',
      'High-sodium processed foods',
    ],
    correctIndex: 1,
    rationale: 'DASH highlights fruits, vegetables, low-fat dairy, whole grains, lean proteins, and nuts — rich in potassium, magnesium, calcium.',
  },
  {
    id: 'ncd-011',
    topic: 'ncd',
    type: 'mcq',
    prompt: 'The recommended daily sodium upper limit in hypertension management is approximately:',
    choices: ['<500 mg', '<1000 mg', '<2000 mg', '<5000 mg'],
    correctIndex: 2,
    rationale: 'Aim for <2000 mg sodium/day (~5 g salt) when managing hypertension.',
  },
  {
    id: 'ncd-012',
    topic: 'ncd',
    type: 'mcq',
    prompt: 'Recommended potassium intake (without contraindication) is approximately:',
    choices: ['500 mg', '1500 mg', '3500–4700 mg', '6000 mg'],
    correctIndex: 2,
    rationale: 'Potassium target is ~3500–4700 mg/day; sources include bananas, spinach, potatoes, legumes.',
  },
  {
    id: 'ncd-013',
    topic: 'ncd',
    type: 'mcq',
    prompt: 'Which fats are preferred over saturated and trans fats?',
    choices: ['MUFAs and PUFAs', 'Lard', 'Coconut oil only', 'Palm oil only'],
    correctIndex: 0,
    rationale: 'Monounsaturated and polyunsaturated fats (e.g., omega-3 and -6 from fatty fish and seed oils) are preferred.',
  },
  {
    id: 'ncd-014',
    topic: 'ncd',
    type: 'mcq',
    prompt: 'Alcohol limit for men in BP (Blood Pressure) management is:',
    choices: ['No more than 1 drink/day', 'No more than 2 drinks/day', 'Up to 4 drinks/day', 'No limit'],
    correctIndex: 1,
    rationale: 'Men: no more than 2 drinks/day. Women: no more than 1 drink/day.',
  },
  {
    id: 'ncd-015',
    topic: 'ncd',
    type: 'mcq',
    prompt: 'Type 2 diabetes is best managed dietarily by:',
    choices: [
      'Eliminating all carbohydrates',
      'Choosing low glycemic index foods, lean protein, healthy fats, and fiber',
      'High-sugar liquid meals',
      'Avoiding all fats',
    ],
    correctIndex: 1,
    rationale: 'Focus on low-GI foods, portion control, regular meals, fiber, and limited refined carbs and added sugars.',
  },
  {
    id: 'ncd-016',
    topic: 'ncd',
    type: 'mcq',
    prompt: 'Gestational diabetes meal advice includes:',
    choices: [
      'Three large meals daily',
      'Small frequent meals, balancing carbs with proteins, avoiding simple sugars',
      'Skipping breakfast',
      'Carbohydrate-only meals',
    ],
    correctIndex: 1,
    rationale: 'Small, frequent meals stabilize blood sugar; balance carbs with proteins and emphasize fiber.',
  },
  {
    id: 'ncd-017',
    topic: 'ncd',
    type: 'mcq',
    prompt: 'The two most common causes of peptic ulcer disease are:',
    choices: [
      'Stress and spicy food',
      'H. pylori infection and NSAID (Non-Steroidal Anti-Inflammatory Drug) use',
      'Smoking and alcohol only',
      'Genetic mutations',
    ],
    correctIndex: 1,
    rationale: 'H. pylori infection and NSAID use account for most peptic ulcers.',
  },
  {
    id: 'ncd-018',
    topic: 'ncd',
    type: 'mcq',
    prompt: 'Which meal pattern is recommended in PUD (Peptic Ulcer Disease)?',
    choices: [
      'Two large meals daily',
      'Three small meals plus three snacks evenly spaced',
      'Drinking citrus juice with each meal',
      'Eating just before bedtime',
    ],
    correctIndex: 1,
    rationale: 'Three small meals and three snacks evenly spaced reduce acid load per meal and avoid hunger/over-eating.',
  },
  {
    id: 'ncd-019',
    topic: 'ncd',
    type: 'mcq',
    prompt: 'In PUD (Peptic Ulcer Disease), which foods are typically AVOIDED because they trigger symptoms?',
    choices: [
      'Bananas and rice',
      'Spicy foods, high-fat meals, caffeine, chocolate, acidic juices, alcohol',
      'Plain yogurt',
      'Boiled potatoes',
    ],
    correctIndex: 1,
    rationale: 'Spicy foods, caffeine, chocolate, citrus, alcohol, and high-fat meals can worsen PUD symptoms.',
  },
  {
    id: 'ncd-020',
    topic: 'ncd',
    type: 'mcq',
    prompt: 'A patient with PUD (Peptic Ulcer Disease) should avoid eating within how many hours before bedtime?',
    choices: ['1 hour', '2 hours', '3 hours', '6 hours'],
    correctIndex: 2,
    rationale: 'Avoid eating within 3 hours before bedtime to prevent nocturnal gastric acid secretion.',
  },
  {
    id: 'ncd-021',
    topic: 'ncd',
    type: 'mcq',
    prompt: 'Which fiber type may help protect the mucosa and reduce gastritis symptoms?',
    choices: ['Insoluble fiber only', 'Soluble fiber', 'Cellulose only', 'No fiber'],
    correctIndex: 1,
    rationale: 'Soluble fiber may protect the gastric mucosa and reduce symptoms.',
  },
  {
    id: 'ncd-022',
    topic: 'ncd',
    type: 'mcq',
    prompt: 'An average adult man needs approximately how many kcal/day to maintain his weight?',
    choices: ['1,500', '2,000', '2,500', '3,500'],
    correctIndex: 2,
    rationale: 'About 2,500 kcal/day for maintenance; ~2,000 kcal/day for ~0.5–1 kg/week weight loss.',
  },
  {
    id: 'ncd-023',
    topic: 'ncd',
    type: 'tf',
    prompt: 'Even modest weight loss can lower blood pressure.',
    correctAnswer: true,
    rationale: 'Blood pressure rises with weight; even a few kilograms of weight loss reduces BP (Blood Pressure).',
  },
  {
    id: 'ncd-024',
    topic: 'ncd',
    type: 'tf',
    prompt: 'Dietary management alone is sufficient to treat peptic ulcer disease.',
    correctAnswer: false,
    rationale: 'Dietary measures are adjunctive; H. pylori eradication, PPIs/H2 blockers, and NSAID (Non-Steroidal Anti-Inflammatory Drug) avoidance are essential.',
  },
  {
    id: 'ncd-025',
    topic: 'ncd',
    type: 'tf',
    prompt: 'A reasonable initial weight-loss target is about 10% of body weight over 6 months.',
    correctAnswer: true,
    rationale: 'Guidelines recommend a 10% weight-loss goal over 6 months for clinically meaningful metabolic improvement.',
  },

  // ============================================================
  // NUTRITION INTERVENTIONS IN GHANA (20)
  // ============================================================
  {
    id: 'ghana-001',
    topic: 'ghana',
    type: 'mcq',
    prompt: 'Optimal breastfeeding should be initiated within:',
    choices: ['The first 5 minutes after birth', 'The first hour after birth', 'The first 6 hours', 'The first day'],
    correctIndex: 1,
    rationale: 'Early initiation within the first hour after birth is recommended.',
  },
  {
    id: 'ghana-002',
    topic: 'ghana',
    type: 'mcq',
    prompt: 'WHO (World Health Organization) recommends continued breastfeeding (alongside complementary foods) up to:',
    choices: ['6 months', '12 months', '2 years or beyond', 'Age 5'],
    correctIndex: 2,
    rationale: 'Continued breastfeeding is recommended up to 2 years or beyond, alongside appropriate complementary foods.',
  },
  {
    id: 'ghana-003',
    topic: 'ghana',
    type: 'mcq',
    prompt: 'The Baby-Friendly Hospital Initiative (BFHI (Baby-Friendly Hospital Initiative)) primarily aims to:',
    choices: [
      'Increase formula feeding access',
      'Promote and support breastfeeding',
      'Reduce hospital costs',
      'Train pediatricians only',
    ],
    correctIndex: 1,
    rationale: 'BFHI is a global initiative to ensure maternity facilities support breastfeeding initiation and continuation.',
  },
  {
    id: 'ghana-004',
    topic: 'ghana',
    type: 'mcq',
    prompt: 'Zinc supplementation for diarrhea in children >6 months is given at:',
    choices: [
      '5 mg daily for 5 days',
      '20 mg daily for 10–14 days',
      '50 mg daily for 30 days',
      '100 mg as a single dose',
    ],
    correctIndex: 1,
    rationale: 'Children >6 months: 20 mg zinc daily for 10–14 days, given with ORT (Oral Rehydration Therapy).',
  },
  {
    id: 'ghana-005',
    topic: 'ghana',
    type: 'mcq',
    prompt: 'For infants <6 months, the daily zinc dose during diarrhea is:',
    choices: ['5 mg', '10 mg', '20 mg', '30 mg'],
    correctIndex: 1,
    rationale: 'Infants <6 months: 10 mg zinc daily during diarrhea.',
  },
  {
    id: 'ghana-006',
    topic: 'ghana',
    type: 'mcq',
    prompt: 'Iron-folic acid supplementation in pregnancy typically includes daily elemental iron of:',
    choices: ['10 mg', '30 mg', '60 mg', '150 mg'],
    correctIndex: 2,
    rationale: '60 mg elemental iron daily throughout pregnancy is standard for routine antenatal supplementation.',
  },
  {
    id: 'ghana-007',
    topic: 'ghana',
    type: 'mcq',
    prompt: 'Daily folic acid dose in routine antenatal IFA (Iron-Folic Acid) supplementation is:',
    choices: ['100 µg', '400 µg', '1 mg', '5 mg'],
    correctIndex: 1,
    rationale: 'Routine antenatal IFA includes 400 µg folic acid daily.',
  },
  {
    id: 'ghana-008',
    topic: 'ghana',
    type: 'mcq',
    prompt: 'Universal salt iodization primarily helps prevent:',
    choices: ['Vitamin A deficiency', 'Goiter and IQ (Intelligence Quotient) deficits', 'Anemia', 'Stunting only'],
    correctIndex: 1,
    rationale: 'Iodized salt prevents goiter and improves cognitive outcomes population-wide.',
  },
  {
    id: 'ghana-009',
    topic: 'ghana',
    type: 'mcq',
    prompt: 'Fortified wheat flour in Ghana is typically enriched with:',
    choices: ['Vitamin A only', 'Iron, folic acid, and B vitamins', 'Calcium only', 'Iodine'],
    correctIndex: 1,
    rationale: 'Fortified wheat flour delivers iron, folic acid, and B-complex vitamins to the population.',
  },
  {
    id: 'ghana-010',
    topic: 'ghana',
    type: 'mcq',
    prompt: 'Fortified vegetable oil in Ghana is enriched with:',
    choices: ['Iron', 'Vitamin A', 'Iodine', 'Zinc'],
    correctIndex: 1,
    rationale: 'Cooking oil fortification with vitamin A is a key population-level strategy.',
  },
  {
    id: 'ghana-011',
    topic: 'ghana',
    type: 'mcq',
    prompt: 'Vitamin A supplementation for children 6–59 months is delivered as:',
    choices: [
      'Daily dosing',
      'High-dose periodic supplementation via routine contacts and Child Health Weeks',
      'Only when blindness is suspected',
      'Only in tertiary hospitals',
    ],
    correctIndex: 1,
    rationale: 'High-dose periodic supplementation is given through routine health contacts and Child Health Weeks.',
  },
  {
    id: 'ghana-012',
    topic: 'ghana',
    type: 'mcq',
    prompt: 'A child diagnosed with MAM (moderate acute malnutrition) is most often managed:',
    choices: [
      'As an inpatient',
      'Through outpatient care, community screening, and follow-up',
      'With insulin therapy',
      'By surgical referral',
    ],
    correctIndex: 1,
    rationale: 'MAM (Moderate Acute Malnutrition) is managed in outpatient settings with food support and community screening.',
  },
  {
    id: 'ghana-013',
    topic: 'ghana',
    type: 'mcq',
    prompt: 'A child diagnosed with SAM (Severe Acute Malnutrition) WITHOUT complications is best treated with:',
    choices: [
      'Hospital-only stabilization',
      'Ready-to-Use Therapeutic Food (RUTF (Ready-to-Use Therapeutic Food)) under the CMAM (Community-based Management of Acute Malnutrition) model',
      'Antibiotics only',
      'Vitamin A megadose alone',
    ],
    correctIndex: 1,
    rationale: 'CMAM model: SAM without complications is treated with RUTF in the community, monitored weekly.',
  },
  {
    id: 'ghana-014',
    topic: 'ghana',
    type: 'mcq',
    prompt: 'The abbreviation ENA stands for:',
    choices: [
      'Essential Nutrition Actions',
      'Effective Nutritional Allowance',
      'Early Nutrition Assistance',
      'Emergency Nutrition Algorithm',
    ],
    correctIndex: 0,
    rationale: 'Essential Nutrition Actions (ENA) is a framework promoting key nutrition behaviours at health contact points.',
  },
  {
    id: 'ghana-015',
    topic: 'ghana',
    type: 'mcq',
    prompt: 'Which is a PRIMARY role of the NURSE in nutrition care?',
    choices: [
      'Designing therapeutic milk formulations',
      'First-contact counselling, malnutrition screening, and breastfeeding support',
      'National policy drafting only',
      'Laboratory analysis of micronutrients',
    ],
    correctIndex: 1,
    rationale: 'Nurses provide first-contact care, screening, referral, breastfeeding support, hygiene promotion, and community outreach.',
  },
  {
    id: 'ghana-016',
    topic: 'ghana',
    type: 'mcq',
    prompt: 'Which is a PRIMARY role of the DIETICIAN/NUTRITIONIST?',
    choices: [
      'Performing surgery',
      'Designing individualized meal plans and therapeutic feeding regimens',
      'Issuing antimalarial medications',
      'Administering vaccines only',
    ],
    correctIndex: 1,
    rationale: 'Dieticians/nutritionists assess, plan therapeutic feeding (MAM (Moderate Acute Malnutrition)/SAM (Severe Acute Malnutrition)), educate, and evaluate nutrition programs.',
  },
  {
    id: 'ghana-017',
    topic: 'ghana',
    type: 'mcq',
    prompt: 'Community-Based Growth Monitoring and Promotion (GMP (Growth Monitoring and Promotion)) regularly tracks:',
    choices: [
      'Hemoglobin only',
      'Weight and MUAC (Mid-Upper Arm Circumference) with caregiver counselling',
      'Insulin levels',
      'Vision testing',
    ],
    correctIndex: 1,
    rationale: 'GMP tracks child growth (weight, MUAC) regularly with caregiver counselling and referral.',
  },
  {
    id: 'ghana-018',
    topic: 'ghana',
    type: 'mcq',
    prompt: 'Which platform combines vitamin A, deworming, immunizations, and growth monitoring in periodic outreach?',
    choices: [
      'Antenatal care visits',
      'Child Health Weeks',
      'School entry assessments',
      'Universal salt iodization',
    ],
    correctIndex: 1,
    rationale: 'Child Health Weeks deliver bundled services biannually with high coverage and community mobilization.',
  },
  {
    id: 'ghana-019',
    topic: 'ghana',
    type: 'tf',
    prompt: 'Workplace breastfeeding policies are recognized as a solution to barriers in optimal breastfeeding.',
    correctAnswer: true,
    rationale: 'Workplace policies, community education, and partner involvement help overcome breastfeeding barriers.',
  },
  {
    id: 'ghana-020',
    topic: 'ghana',
    type: 'tf',
    prompt: 'Handwashing at critical times (e.g., after toilet, before food preparation) is part of nutrition interventions.',
    correctAnswer: true,
    rationale: 'WASH (Water, Sanitation, and Hygiene) practices are integrated into nutrition counselling because poor hygiene drives infections that worsen nutrition.',
  },
];

export function getQuestionsByTopics(
  topics: NutritionTopic[],
  count: number,
): NutritionQuestion[] {
  const pool = nutritionQuestions.filter((q) => topics.includes(q.topic));
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}
